#!/usr/bin/env python3
"""Generate index/manifest.json and docs/STATUS.md from the repo tree.

Usage:
  python3 scripts/build_index.py            # regenerate both files
  python3 scripts/build_index.py --check    # validate only; exit 1 on errors

Errors (exit 1): content file missing frontmatter; manifest stale (--check).
Warnings (exit 0): incomplete lessons/exams/IELTS tests; exercise.md without
an embedded '## ANSWER KEY' heading. Stdlib only.
"""
from __future__ import annotations

import argparse
import datetime
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from curriculum_lib import classify, has_frontmatter, scan_repo  # noqa: E402

CONTENT_GLOBS = ("phase_*/*/*.md", "ielts_practice_tests/test_*/*.md")


def validate(root: Path, data: dict) -> tuple[list[str], list[str]]:
    errors, warnings = [], []
    for pattern in CONTENT_GLOBS:
        for path in sorted(root.glob(pattern)):
            rel = path.relative_to(root)
            if classify(rel) is None:
                continue
            text = path.read_text(encoding="utf-8")
            if not has_frontmatter(text):
                errors.append(f"missing frontmatter: {rel}")
            if rel.name == "exercise.md" and "## ANSWER KEY" not in text:
                warnings.append(f"exercise without '## ANSWER KEY' heading: {rel}")
    for phase in data["phases"]:
        for lesson in phase["lessons"]:
            for fname, ok in lesson["files"].items():
                if not ok:
                    warnings.append(f"incomplete lesson: {lesson['dir']} missing {fname}")
        exam = phase["exam"]
        if exam:
            if not exam["exam"]:
                warnings.append(f"missing exam file in {exam['dir']}")
            if not exam["answer_key"]:
                warnings.append(f"missing answer key in {exam['dir']}")
    for test in data["ielts_tests"]:
        for fname, ok in test["files"].items():
            if not ok:
                warnings.append(f"incomplete IELTS test: {test['dir']} missing {fname}")
    return errors, warnings


def mark(ok: bool) -> str:
    return "✅" if ok else "❌ MISSING"


def render_status(data: dict) -> str:
    today = datetime.date.today().isoformat()
    out = [
        "# CURRICULUM STATUS",
        "",
        f"> Generated by `scripts/build_index.py` on {today}.",
        "> Do not edit by hand — run `python3 scripts/build_index.py` to refresh.",
        "",
    ]
    for phase in data["phases"]:
        done = sum(1 for l in phase["lessons"] if l["complete"])
        out += [
            f"## Phase {phase['number']} — {phase['name'].replace('_', ' ')} ({phase['cefr']})",
            "",
            f"{done}/{len(phase['lessons'])} lessons complete.",
            "",
            "| Lesson | lecture.md | vocabulary.md | exercise.md | Score reports |",
            "|---|:-:|:-:|:-:|---|",
        ]
        for lesson in phase["lessons"]:
            name = lesson["dir"].split("/", 1)[1]
            cells = [mark(lesson["files"][f]) for f in
                     ("lecture.md", "vocabulary.md", "exercise.md")]
            reports = ", ".join(lesson["score_reports"]) or "—"
            out.append(f"| {name} | {cells[0]} | {cells[1]} | {cells[2]} | {reports} |")
        exam = phase["exam"]
        if exam:
            out += ["", f"Exam: {mark(exam['exam'])} exam file, "
                        f"{mark(exam['answer_key'])} answer key ({exam['dir']})"]
        out.append("")
    complete = sum(1 for t in data["ielts_tests"] if t["complete"])
    out += [
        "## IELTS practice tests",
        "",
        f"{complete}/{len(data['ielts_tests'])} tests complete (4/4 files).",
        "",
        "| Test | reading | writing | speaking | answer key | Score reports |",
        "|---|:-:|:-:|:-:|:-:|---|",
    ]
    for test in data["ielts_tests"]:
        name = test["dir"].split("/", 1)[1]
        cells = [mark(test["files"][f]) for f in
                 ("reading.md", "writing.md", "speaking.md", "answer_key.md")]
        reports = ", ".join(test["score_reports"]) or "—"
        out.append(f"| {name} | {' | '.join(cells)} | {reports} |")
    out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(args.root).resolve()

    data = scan_repo(root)
    errors, warnings = validate(root, data)

    if args.check:
        manifest_path = root / "index" / "manifest.json"
        if manifest_path.is_file():
            stored = json.loads(manifest_path.read_text(encoding="utf-8"))
            stored.pop("generated_at", None)
            if stored != data:
                errors.append("index/manifest.json is stale — run: python3 scripts/build_index.py")
        else:
            errors.append("index/manifest.json does not exist — run: python3 scripts/build_index.py")
    else:
        manifest = dict(data)
        manifest["generated_at"] = datetime.date.today().isoformat()
        (root / "index").mkdir(exist_ok=True)
        (root / "index" / "manifest.json").write_text(
            json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        (root / "docs").mkdir(exist_ok=True)
        (root / "docs" / "STATUS.md").write_text(render_status(data), encoding="utf-8")
        print("wrote index/manifest.json and docs/STATUS.md")

    for warning in warnings:
        print(f"WARN: {warning}")
    for error in errors:
        print(f"ERROR: {error}", file=sys.stderr)
    print(f"{len(errors)} errors, {len(warnings)} warnings")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
